ART_VERSION=6.9.5
CONTAINER_NAME=RTFACT-7668_$ART_VERSION
echo pulling...
docker pull docker.bintray.io/jfrog/artifactory-pro:$ART_VERSION
echo running...
docker run --name $CONTAINER_NAME -d -p 8081:8081 docker.bintray.io/jfrog/artifactory-pro:$ART_VERSION

echo copying...
docker cp ./from-npm/ $CONTAINER_NAME:/
